import Sidebar from "@/lib/modules/sidebar/Sidebar";
import HttpService from "@/lib/utils/HttpService";
import { Routes } from "@/lib/constants/ApiRoutes";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  params,
  children,
}: {
  children: React.ReactNode;
  params: any;
}) {
  let content = <></>;

  try {
    const games = await HttpService.get(Routes.GAMES_GET_ALL, {
      name: "melee",
    });
    const cookbooks = await HttpService.get(Routes.COOKBOOK_GET_ALL, {
      game: games[0]?._id,
      name: params.cookbook,
    });
    const guides = await HttpService.get(
      Routes.GUIDES_GET_ALL(cookbooks[0]?._id)
    );

    content = (
      <>
        <Sidebar cookbook={cookbooks[0]} guides={guides} />
        {children}
      </>
    );
  } catch (err) {
    console.log(err);
    content = <>Error</>;
  }

  return <div className="flex">{content}</div>;
}
