import Sidebar from "@/lib/ui/sidebar/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import HttpService from "@/lib/utils/HttpService";
import { Routes } from "@/lib/constants/ApiRoutes";
import { useStore } from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: {
  children: React.ReactNode;
  params: any;
}) {
  const cookbooks = await HttpService.get(Routes.COOKBOOK_GET_ALL);
  useStore.setState({ cookbooks });

  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gray-900 flex overflow-hidden h-screen`}
      >
        <Sidebar cookbooks={cookbooks} />
        {children}
      </body>
    </html>
  );
}
